# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set of functions that maximize the regression slope for the OLS estimate
#' of univariate linear regression parameters. These functions were written
#' to handle the special case where 
#' 1. only the k-largest values of the target are known,
#' 2. the sum of all target values is known, and
#' 3. both the predictor and the target are positive integers excluding zero
NULL

#' Report progress
NULL

#' Loss function
#'
lossFn_cpp <- function(z, n, ln_xr, sum_ln_x, k) {
    .Call(`_topkOptim_lossFn_cpp`, z, n, ln_xr, sum_ln_x, k)
}

#' Optimize
#' 
#' @param xr The x-values not in the top-k.
#' @param x The x-values.
#' @param z0 The vector of starting values for the optimization.
#' @param steps The number of optimization steps.
#' @param maxZ The maximum value of elements of z.
#' @param maximize Whether to maximize.
#' @param verbose Whether to report progress.
#' 
#' @description
#' Using the OLS equation for regression parameters, this function
#' maximizes or minimizes the regression slope subject to the following
#' conditions
#' 1. The predictor is completely observed
#' 2. Only the k-largest values of the target are observed
#' 3. The sum of the entire target variable is observed
#' 
#' This function assumes that the domain of both x and z are non-negative 
#' integers excluding zero.
#' 
#' If the function is called with `maximum != 1`, it will return the solution
#' that minimizes the regression slope.
#' 
optim <- function(xr, x, z0, steps, maxZ, maximize = 1L, verbose = 0L) {
    .Call(`_topkOptim_optim`, xr, x, z0, steps, maxZ, maximize, verbose)
}

#' Optimize on Grouped Data
#'
#' @param x_data See details.
#' @param index See details.
#' @param maximize Whether to maximize.
#' @param verbose Whether to report progress.
#'
#' @description
#' A version of `optim()` designed to be used when the data are grouped.
#'
#' @details
#' This function optimizes the OLS regression slope subject to the same conditions as
#' `optim()`, but allows for the data to be grouped such that 
#' each group has its own optimization constraints and maximum number of 
#' optimization steps. The expectation is that the data represents cities grouped by state.
#' 
#' The \code{x_data} argument should be a dataframe containing city populations.
#' This data frame should have columns called \code{state}, the state in which
#' that city is located; \code{x}, the city population; and \code{isTopK},
#' `1` when that city is in the top-K and `0` otherwise.
#' 
#' The \code{index} object should be a dataframe containing the optimization
#' parameters for each state, to be used as a look-up table. This dataframe 
#' should have columns called \code{state}, \code{steps}, the number of recovered
#' firearms in that state; and \code{maxZ}, the maximum number of firearms that could be 
#' recovered in a non-top-K city.
#'
optim_aggregate <- function(x_data, index, maximize = 1L, verbose = 0L) {
    .Call(`_topkOptim_optim_aggregate`, x_data, index, maximize, verbose)
}

